In [1]:
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote
import numpy as np

password = quote('ab@sql123')
engine = create_engine(
    f'mysql+pymysql://root:{password}@127.0.0.1:3306/inventory'
)
# get all table names
query = "SHOW TABLES"
tables_df = pd.read_sql(query, con=engine)
tables = tables_df.iloc[:, 0].tolist()

print(tables)

['begin_inventory', 'end_inventory', 'purchase_prices', 'purchases', 'sales', 'vendor_invoice', 'vendor_sales_summary']

Load all the tables data

In [2]:

for table in tables:
    print('_'*50, table, '_'*50)
    
    display(pd.read_sql(
        f"SELECT * FROM `{table}` LIMIT 5",
        con=engine
    ))

__________________________________________________ begin_inventory __________________________________________________

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

__________________________________________________ end_inventory __________________________________________________

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

__________________________________________________ purchase_prices __________________________________________________

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

__________________________________________________ purchases __________________________________________________

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

__________________________________________________ sales __________________________________________________

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

__________________________________________________ vendor_invoice __________________________________________________

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,

__________________________________________________ vendor_sales_summary __________________________________________________

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,28704,181245.64,1033056.96,52739.45,68601.68,307706.88,29.786052,0.197849,0.271055
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,26388,147306.78,796658.12,48484.23,144929.24,153050.40,19.211553,0.160865,0.209424
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,34797,129244.87,878099.03,63935.10,123780.22,234879.75,26.748663,0.185676,0.256882
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,55863,118860.68,1244082.37,102644.09,257032.07,380985.66,30.623829,0.276986,0.381480
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,29850,143754.47,915561.50,54845.56,257032.07,241785.00,26.408384,0.216134,0.302845



EDA----------------

In [3]:
purchase_prices = pd.read_sql_query("""select * from purchase_prices where VendorNumber = 4466""", con=engine)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [4]:
purchases = pd.read_sql_query("""select * from purchases where VendorNumber = 4466""", con=engine)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [5]:
vendor_invoice = pd.read_sql_query("""select * from vendor_invoice where VendorNumber = 4466""", con=engine)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,

In [6]:
sales = pd.read_sql_query("""select * from sales where VendorNo = 4466""", con=engine)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9185,6_GOULCREST_3140,6,3140,TGI Fridays Orange Dream,1.75L,1,12.99,12.99,2024-12-19,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9186,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-10,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9187,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9188,6_GOULCREST_5255,6,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9189,6_GOULCREST_5255,6,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-24,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [8]:
vendor_invoice['PONumber'].nunique()

55

In [9]:
sales.groupby('Brand')[['SalesDollars', 'SalesPrice', 'SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       49465.92    29201.52           3808
5215       58688.82    40269.00           4518
5255       77225.55    49907.58           5945

In [ ]:
  • The purchases table contains actual purchase data, including the date Of purchase, products (brands) purchased by vendors, the amount paid (in dollars), and the quantity purchased.

  • The purchase price column is derived from the purchase_prices table, which provides product-wise actual and purchase prices, The combination of vendor and brand is unique in this table.

  • The vendor_invoice table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.

  • The sales table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

As the data that we need for analysis is distributed in different tables. we need to create a summary table containing:
  • purchase transactions made by vendors
  • sales transaction data
  • freight costs for each vendor
  • actual product prices front vendors

In [10]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [11]:
freight_summary = pd.read_sql_query("""SELECT VendorNumber, SUM(Freight) AS FreightCost
FROM vendor_invoice
Group BY VendorNumber""", con=engine )

freight_summary

     VendorNumber  FreightCost
0             105        62.39
1            4466       793.91
2             388       211.74
3             480     89286.27
4             516      8510.41
..            ...          ...
121        201359         0.09
122          4901         0.72
123         90059        74.84
124          5083        10.68
125            54         0.48

[126 rows x 2 columns]

In [12]:
pd.read_sql_query('''
SELECT 
    p.VendorNumber, 
    p.VendorName, 
    p.Brand, 
    p.PurchasePrice, 
    pp.volume, 
    pp.price AS Actual_price,
    SUM(p.quantity) AS total_purchase_quantity, 
    SUM(p.Dollars) AS total_purchase_dollar 
FROM purchases p 
JOIN purchase_prices pp ON p.Brand = pp.Brand 
WHERE p.PurchasePrice > 0 
GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.PurchasePrice, pp.volume, pp.price
ORDER BY total_purchase_dollar
''', con=engine)

,VendorNumber,VendorName,Brand,PurchasePrice,volume,Actual_price,total_purchase_quantity,total_purchase_dollar
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1.0,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1.0,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2.0,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6.0,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2.0,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60

In [13]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [14]:
pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars
""", con=engine)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,9.800000e-01,0.98,2.0,0.10
1,9206,2773,9.900000e-01,0.99,1.0,0.05
2,3252,3933,1.980000e+00,0.99,2.0,0.10
3,10050,3623,1.980000e+00,1.98,2.0,0.10
4,660,2134,2.490000e+00,2.49,1.0,0.39
...,...,...,...,...,...,...
11245,3960,3545,4.137756e+06,537111.17,132992.0,244358.52
11246,3960,4261,4.356561e+06,414172.81,194723.0,357789.51
11247,17035,8068,4.465724e+06,454633.42,184058.0,338191.12
11248,4425,3405,4.713550e+06,553395.17,156607.0,287750.42
11249,1128,1233,5.012345e+06,663057.10,139489.0,256295.49

In [ ]:
#import time
#start = time.time()

#final_table = pd.read_sql_query("""
#SELECT
   # pp.VendorNumber,
   # pp.Brand,
   # pp.Price AS ActualPrice,
   # pp.PurchasePrice,
    #SUM(s.SalesQuantity) AS TotalSalesQuantity,
     #SUM(s.SalesDollars) AS TotalSalesDollars,
    # SUM(s.SalesPrice) AS TotalSalesPrice,
    # SUM(s.ExciseTax) AS TotalExciseTax,
    # SUM(vi.Quantity) AS TotalPurchaseQuantity,
    # SUM(vi.Dollars) AS TotalPurchaseDollars,
    # SUM(vi.Freight) AS TotalFreightCost
 #FROM purchase_prices pp

 #JOIN sales s
   #  ON pp.VendorNumber = s.VendorNo
    # AND pp.Brand = s.Brand
    
 #JOIN vendor_invoice vi
     #ON pp.VendorNumber = vi.VendorNumber

 #GROUP BY 
    # pp.VendorNumber, 
    # pp.Brand, 
    # pp.Price, 
    # pp.PurchasePrice
 #, con=engine)

 #end = time.time()

final dataframe with optimized query

In [15]:
vendor_sales_summary = pd.read_sql_query("""WITH FreightSummary AS(
    SELECT
        VendorNumber,
        SUM(Freight) AS FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary AS (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price AS ActualPrice,
        pp.Volume,
        SUM(p.Quantity) AS TotalPurchaseQuantity,
        SUM(p.Quantity * p.PurchasePrice) AS TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY p.VendorNumber, p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume
),

SalesSummary AS(
    SELECT
        VendorNo,
        Brand,
        SUM(SalesQuantity) AS TotalSalesQuantity,
        SUM(SalesDollars) AS TotalSalesDollars,
        SUM(SalesPrice) AS TotalSalesPrice,
        SUM(ExciseTax) AS TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand 
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesPrice,
    ss.TotalSalesDollars,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC"""
,con=engine)

In [16]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080.0,3811251.60,139489.0,663057.10,5.012345e+06,256295.49,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038.0,3804041.22,156607.0,553395.17,4.713550e+06,287750.42,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407.0,3418303.68,184058.0,454633.42,4.465724e+06,338191.12,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682.0,3261197.94,194723.0,414172.81,4.356561e+06,357789.51,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109.0,3023206.01,132992.0,537111.17,4.137756e+06,244358.52,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2.0,2.64,5.0,10.96,1.595000e+01,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6.0,2.34,134.0,1.47,6.566000e+01,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2.0,1.48,NaN,NaN,NaN,NaN,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1.0,1.47,72.0,77.61,1.432800e+02,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1.0,0.71,86.0,33.66,8.514000e+01,4.46,38994.78

This query generates a vendor-wise sales and purchase summary, which is valuable for:

Preformance Optimization:

1. The query involves heavy joins and aggregations on large datasets like sales and purchases.    
2. Storing the pre-aggregates results avoids repeated expensive computations.
3. Helps in analyzing sales, purchases, and pricing for different vendors and brands.
4. Future Benefits of Storing the data for faster Dashboarding and Reporting.
5. Instead of running expensive queries each time, dashboards can fetch data quickly from vendor_sales_summary.

In [17]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                       str
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesPrice          float64
TotalSalesDollars        float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [18]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesQuantity       200
TotalSalesPrice          200
TotalSalesDollars        200
TotalExciseTax           200
FreightCost                0
dtype: int64

In [19]:
# Fill missing values with 0
cols_to_fix = ['TotalSalesQuantity', 'TotalSalesPrice', 'TotalSalesDollars', 'TotalExciseTax']
vendor_sales_summary[cols_to_fix] = vendor_sales_summary[cols_to_fix].fillna(0)

# Verify the fix
print(vendor_sales_summary.isnull().sum())

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesPrice          0
TotalSalesDollars        0
TotalExciseTax           0
FreightCost              0
dtype: int64

In [20]:
vendor_sales_summary['VendorName'].unique()

<StringArray>
['BROWN-FORMAN CORP          ',       'MARTIGNETTI COMPANIES',
 'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
 'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
 'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
 'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
 ...
             'UNCORKED       ', 'BRONCO WINE COMPANY        ',
 'MILTONS DISTRIBUTING CO    ', 'TRUETT HURST               ',
 'LAUREATE IMPORTS CO        ', 'FANTASY FINE WINES CORP    ',
 'AAPER ALCOHOL & CHEMICAL CO', 'SILVER MOUNTAIN CIDERS     ',
 'CAPSTONE INTERNATIONAL     ', 'FLAVOR ESSENCE INC         ']
Length: 129, dtype: str

In [21]:
# Convert Volume to numeric (stripping 'mL' if necessary, though SQL results usually handle this)
vendor_sales_summary['Volume'] = pd.to_numeric(vendor_sales_summary['Volume'], errors='coerce')

# Convert Quantities to Integers
cols_to_int = ['TotalPurchaseQuantity', 'TotalSalesQuantity']
vendor_sales_summary[cols_to_int] = vendor_sales_summary[cols_to_int].astype('int64')

# Optional: Strip whitespace from VendorName (seen in your unique() output)
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

print(vendor_sales_summary.dtypes)

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity         int64
TotalSalesPrice          float64
TotalSalesDollars        float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

FEATURE CREATION

In [23]:
# Calculate Gross Profit based on units actually sold
vendor_sales_summary["GrossProfit"] = vendor_sales_summary['TotalSalesQuantity'] * (vendor_sales_summary['ActualPrice'] - vendor_sales_summary['PurchasePrice'])

In [24]:
# Profit Margin (%) - Revenue based
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) * 100
vendor_sales_summary['ProfitMargin'] = vendor_sales_summary['ProfitMargin'].replace([np.inf, -np.inf], 0).fillna(0)

In [25]:
#Stock Turnover
vendor_sales_summary['StockTurnover'] = vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [26]:
#Sales to Purchase Ratio
vendor_sales_summary['SalestoPurchaseRatio'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [27]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,139489,663057.10,5.012345e+06,256295.49,68601.68,1495322.08,29.832784,0.961463,1.315144
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,156607,553395.17,4.713550e+06,287750.42,144929.24,908320.60,19.270414,0.954700,1.239090
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,184058,454633.42,4.465724e+06,338191.12,123780.22,1242391.50,27.820604,0.982130,1.306415
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,194723,414172.81,4.356561e+06,357789.51,257032.07,1328010.86,30.483010,0.965495,1.335877
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,132992,537111.17,4.137756e+06,244358.52,257032.07,1077235.20,26.034285,0.962950,1.368665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5,10.96,1.595000e+01,0.55,27100.41,18.35,115.047022,2.500000,6.041667
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134,1.47,6.566000e+01,7.04,50293.62,13.40,20.408163,22.333333,28.059829
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,0,0.00,0.000000e+00,0.00,14069.87,0.00,0.000000,0.000000,0.000000
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72,77.61,1.432800e+02,15.12,257032.07,37.44,26.130653,72.000000,97.469388
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86,33.66,8.514000e+01,4.46,38994.78,24.08,28.282828,86.000000,119.915493

In [28]:
from sqlalchemy import text

# Use the existing 'engine' from  first cell
with engine.connect() as con:
    # Wrap your SQL strings in the text() function
    con.execute(text("DROP TABLE IF EXISTS vendor_sales_summary"))
    
    con.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber INT, 
            VendorName VARCHAR(255), 
            Brand INT, 
            Description VARCHAR(255), 
            PurchasePrice DECIMAL(15,2), 
            ActualPrice DECIMAL(15,2), 
            Volume DECIMAL(15,2), 
            TotalPurchaseQuantity INT, 
            TotalPurchaseDollars DECIMAL(15,2), 
            TotalSalesQuantity INT, 
            TotalSalesPrice DECIMAL(15,2), 
            TotalSalesDollars DECIMAL(15,2), 
            TotalExciseTax DECIMAL(15,2), 
            FreightCost DECIMAL(15,2), 
            GrossProfit DECIMAL(15,2), 
            ProfitMargin DECIMAL(15,2), 
            StockTurnover DECIMAL(15,2), 
            SalestoPurchaseRatio DECIMAL(15,2), 
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))
    con.commit()

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesPrice, TotalSalesDollars, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalestoPurchaseRatio]
Index: []

In [29]:
from sqlalchemy import text

# Use the existing 'engine' from your first cell
with engine.connect() as con:
    # Wrap your SQL strings in the text() function
    con.execute(text("DROP TABLE IF EXISTS vendor_sales_summary"))
    
    con.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber INT, 
            VendorName VARCHAR(255), 
            Brand INT, 
            Description VARCHAR(255), 
            PurchasePrice DECIMAL(15,2), 
            ActualPrice DECIMAL(15,2), 
            Volume DECIMAL(15,2), 
            TotalPurchaseQuantity INT, 
            TotalPurchaseDollars DECIMAL(15,2), 
            TotalSalesQuantity INT, 
            TotalSalesPrice DECIMAL(15,2), 
            TotalSalesDollars DECIMAL(15,2), 
            TotalExciseTax DECIMAL(15,2), 
            FreightCost DECIMAL(15,2), 
            GrossProfit DECIMAL(15,2), 
            ProfitMargin DECIMAL(15,2), 
            StockTurnover DECIMAL(15,2), 
            SalestoPurchaseRatio DECIMAL(15,2), 
            PRIMARY KEY (VendorNumber, Brand)
        );
    """))
    # Note: If using SQLAlchemy 2.0, you may also need to call con.commit() 
    # if you aren't using a transaction block.
    con.commit()

In [30]:


# Replace infinity values with 0
vendor_sales_summary.replace([np.inf, -np.inf], 0, inplace=True)

# Also a good idea to catch any new NaNs created during calculation
vendor_sales_summary.fillna(0, inplace=True)

# Now try the export again
vendor_sales_summary.to_sql('vendor_sales_summary', con=engine, if_exists='replace', index=False)

10692

In [31]:
# This automatically creates the table and handles data types
vendor_sales_summary.to_sql('vendor_sales_summary', con=engine, if_exists='replace', index=False)

10692

In [44]:
pd.read_sql_query("SELECT * FROM vendor_sales_summary LIMIT 5", con=engine)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesPrice,TotalSalesDollars,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalestoPurchaseRatio
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,28704,181245.64,1033056.96,52739.45,68601.68,307706.88,29.786052,0.197849,0.271055
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,26388,147306.78,796658.12,48484.23,144929.24,153050.40,19.211553,0.160865,0.209424
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,34797,129244.87,878099.03,63935.10,123780.22,234879.75,26.748663,0.185676,0.256882
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,55863,118860.68,1244082.37,102644.09,257032.07,380985.66,30.623829,0.276986,0.381480
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,29850,143754.47,915561.50,54845.56,257032.07,241785.00,26.408384,0.216134,0.302845

In [32]:
# if_exists='append' adds the data to the table you just created
vendor_sales_summary.to_sql('vendor_sales_summary', con=engine, if_exists='append', index=False)

print("Data successfully uploaded to SQL!")
vendor_sales_summary.to_csv('vendor_sales_summary.csv', index=False)

Data successfully uploaded to SQL!